### ISSUE TITLE
Make any existing item throwable

### ISSUE THREAD

**Issue by tacotexmex** [Mynetest/throwing#1]
I want to create a bow-like item that can throw any item, much like this [slingshot](https://forum.minetest.net/viewtopic.php?t=13634). Can the API be extended to handle that need?

**Comment by paly2** [comment]
Interesting idea. The arrow registration API was extended a lot, but not the bow registration API. It could be very useful to allow to register bows that can throw any item, and items that can be threw themselves.

I'm implementing it 😃

**Comment by tacotexmex** [comment]
That is awesome, can't wait for it! Good luck!

**Comment by paly2** [comment]
Done!

For example, this bow is able to throw any `default:wood` item:
```lua
throwing.register_bow("test:bow_wood", {
    description = "Bow throwing wood",
    texture = "default_wood.png",
    allow_shot = function(player, itemstack)
        return itemstack:get_name() == "default:wood"
        -- Simply use `return true` to throw any item
        -- Or `return itemstack:get_name() ~= ""` to prevent it to throw an empty item
    end
})
```
You may also want to register an entity to prevent this super-useful bow to throw a `__builtin:item`, and add a `throwing_entity` field containing its name. E.g.
```lua
throwing.register_bow("test:bow_test", {
    description = "Bow throwing wood",
    texture = "default_wood.png",
    allow_shot = function(player, itemstack)
        return itemstack:get_name() == "default:wood"
    end,
    throwing_entity = "test:wood_entity"
})
```
This entity can itself contain almost the same fields as passed to `throwing.register_arrow`:
* `target`
* `allow_protected`
* `on_hit_sound`
* `function on_hit(pos, last_pos, node, object, hitter, data, self)`
* `function on_throw(pos, thrower, next_index, data, self)`

(Refer to the README.md for more informations on these fields)

And this bow throws itself:
```lua
throwing.register_bow("test:bow_itself", {
    description = "Bow throwing itself",
    texture = "default_cobble.png",
    throw_itself = true
})
```

Again, a `throwing_entity` field may be very useful.

**Comment by tacotexmex** [comment]
Excellent! That was _fast_. Will try this out soon. Does`itemstack:get_name()` work on node groups too? :)

**Comment by paly2** [comment]
> Does itemstack:get_name() work on node groups too? :)

`itemstack` is the ItemStack of the arrow (or item) to be threw, if you want to check if it belongs to group "group" you can use:
```lua
allow_shot = function(player, itemstack)
    return minetest.get_item_group(itemstack:get_name(), "group") ~= 0
end
```

**Comment by tacotexmex** [comment]
Sweet! Thank you for explaining how to use it. I'm doing a test mod now.

**Comment by tacotexmex** [comment]
```
throwing.register_bow("sling:sling", {
    description = "Sling",
    texture = "sling_sling_inv.png",
    wield_image = "sling_sling_wield.png",
    allow_shot = function(player, itemstack)
        return itemstack:get_name() ~= ""
    end,
    throwing_entity = "sling:sling_entity",
})
```
This works. But then I want to add throw sound and hit sound. I don't understand how I fill up throwing_entity. Care to show me?

**Comment by paly2** [comment]
Sorry, my explanation was not very good.

If the field `throwing_entity` is not set and the item to throw is not an arrow, the entity thrown is a `__builtin:item` - that is, what you get when you drop an item.

The `throwing_entity` field allows you to use a custom entity instead. In order to use it, you must first register an entity using `minetest.register_entity`. Then you must set `throwing_entity` to the name of this registered entity (you can also set it a function(pos, thrower) that is called to spawn the entity and must return the corresponding `ObjectRef`).

You can pass additional, special fields to `minetest.register_entity` that throwing will use. These fields are:
* `target`: `throwing.target_node`, `throwing.target_object` or `throwing.target_both`
* `allow_protected`: `true` or `false`, whether the entity can be threw in a protected area
* `on_hit_sound`: name of the sound to be played
* `function on_hit(pos, last_pos, node, object, hitter, data, self)`: function called when the entity hits its target
* `function on_throw(pos, thrower, next_index, data, self)`: function called when the entity is thrown.

**Comment by tacotexmex** [comment]
Oh okay!

I'm trying this, but the entity doesn't behave any different based on my custom fields:

```
throwing.register_bow("sling:sling", {
  description = "Sling",
  texture = "sling_sling_inv.png",
  wield_image = "sling_sling_wield.png",
  allow_shot = function(player, itemstack)
      return itemstack:get_name() ~= ""
  end,
  throwing_entity = "sling:sling_entity",
})

minetest.register_entity("sling:sling_entity",{
  hp_max = 1,
  physical = true,
  weight = 5,
  is_visible = true,
  makes_footstep_sound = false,
  automatic_rotate = false,

  target = "throwing.target_node",
  on_hit_sound = "throwing_teleport_arrow",
  on_throw_sound = "throwing_build_arrow",
})
```

**Comment by paly2** [comment]
First you should add `throw_itself = true` in the bow definition, otherwise it will try to throw the item next to it in the inventory (also, the `throwing_entity` field must be part of the thrown item, that's why it didn't change anything if the throw was not thrown itself).

Then the `target` field doesn't expect a string, simply the value contained in `throwing.target_node` 😃 So you must remove the quotes and just write `target = throwing.target_node`.

Next the entity must not be physical, otherwise the collision is handled by the core and cannot be detected by the mod.

Finally, I realized that the target on the on_throw_sound couldn't work if the entity step and some other fields were not set by throwing itself, so I added a `throwing.make_arrow_def` public function. You should also add an `item` field to the entity definition corresponding to the true bow item, which is used for logging and to make the arrow getting back into your inventory in case the hit fails (e.g. if it falls in a protected area while `allow_protected` is set to `false`).

So this code should work:
```lua
throwing.register_bow("sling:sling", {
  description = "Sling",
  texture = "sling_sling_inv.png",
  wield_image = "sling_sling_wield.png",
  allow_shot = function(player, itemstack)
      return itemstack:get_name() ~= ""
  end,
  throwing_entity = "sling:sling_entity",
  throw_itself = true,
})

minetest.register_entity("sling:sling_entity", throwing.make_arrow_def{
  hp_max = 1,
  physical = false,
  weight = 5,
  is_visible = true,
  makes_footstep_sound = false,
  automatic_rotate = false,

  target = throwing.target_node,
  on_hit_sound = "throwing_teleport_arrow",
  on_throw_sound = "throwing_build_arrow",
  item = "sling:sling"
})

```

**Comment by tacotexmex** [comment]
> it will try to throw the item next to it in the inventory

That is what I'm trying to achieve, but with on_hit_sound and on_throw_sound. I do not want to throw the sling itself. It's already doing what it's supposed to without the entity registration, I just want the sound part.

**Comment by paly2** [comment]
Oh, okay, sorry! Then you need to override the item you want to throw and to add the `throwing_entity` field  to its definition, e.g.
```lua
minetest.registered_items["item:name"].throwing_entity = "sling:sling_entity"
```
Also the `item` field of the entity must be set to this item.

But I guess you wish the sling to be able to throw any item. Currently this is not possible with a custom entity, but I'll implement some way to do it tomorrow :)

**Comment by tacotexmex** [comment]
You are correct, I want it to throw any item. 

That is much appreciated, thank you! This is a fine mod and API you're making. :tada:

**Comment by paly2** [comment]
Thanks!

I added a `spawn_arrow_entity` field that allows the bow to define its own entity spawning function.

This code should do what you want:
```lua
throwing.register_bow("test:sling", {
  description = "Sling",
  texture = "sling_sling_inv.png",
  wield_image = "sling_sling_wield.png",
  allow_shot = function(player, itemstack)
      return itemstack:get_name() ~= ""
  end,
  spawn_arrow_entity = function(pos, arrow, player)
    local obj = minetest.add_entity(pos, "sling:sling_entity")
    obj:set_properties({
      textures = {arrow},
      is_visible = true
    })
    return obj
  end
})

minetest.register_entity("sling:sling_entity", throwing.make_arrow_def{
  hp_max = 1,
  physical = false,
  weight = 5,
  is_visible = true,
  makes_footstep_sound = false,
  automatic_rotate = false,
  visual = "wielditem",
  is_visible = false,

  target = throwing.target_node,
  on_hit_sound = "throwing_teleport_arrow",
  on_throw_sound = "throwing_build_arrow"
})

```

**Comment by tacotexmex** [comment]
Very nice, I'll try it out soon! I wonder, by replacing __builtin:item with my own entity, a thrown item is can still be picked up as the same item, right? (Just making sure. My sling project is meant for throwing resources to each other in multiplayer. Sorry for being noobish, I'm doing the best I can with my newfound Lua skills. 😊 )

**Comment by paly2** [comment]
Not with the code in my previous comment, but you can easily change it to make it possible by adding a `on_hit` field:
```lua
throwing.register_bow("sling:sling", {
  description = "Sling",
  texture = "sling_sling_inv.png",
  wield_image = "sling_sling_wield.png",
  allow_shot = function(player, itemstack)
      return itemstack:get_name() ~= ""
  end,
  spawn_arrow_entity = function(pos, arrow, player)
    local obj = minetest.add_entity(pos, "sling:sling_entity")
    obj:set_properties({
      textures = {arrow},
      is_visible = true
    })
    return obj
  end
})

minetest.register_entity("sling:sling_entity", throwing.make_arrow_def{
  hp_max = 1,
  physical = false,
  weight = 5,
  is_visible = true,
  makes_footstep_sound = false,
  automatic_rotate = false,
  visual = "wielditem",
  is_visible = false,

  target = throwing.target_node,
  on_hit_sound = "throwing_teleport_arrow",
  on_throw_sound = "throwing_build_arrow",
  on_hit = function(pos, last_pos, node, object, hitter, data, self)
    minetest.spawn_item(last_pos, self.item) -- the item field is automatically filled by throwing itself :)
  end
})
```

**Comment by tacotexmex** [comment]
Okay, good! I wonder if there will be a visual glitch with `minetest.spawn_item`, but I should see that for myself before pestering you about it. Thanks!

**Comment by tacotexmex** [comment]
A side thought after these discussions: Why not give the bow it's own `on_throw_sound`? In the case of real bows, it's the bowstring that makes the sound when releasing it (though the arrow makes a small sound as well). It would make bow definition more flexible (and my mod simple and short 😁 )

**Comment by paly2** [comment]
> I wonder if there will be a visual glitch with minetest.spawn_item

Well, in fact there will be one :p The only way to avoid it would be to use the default `__builtin:item`, but you won't be able to set a on_hit_sound (on_throw_sound will still work):
```lua
throwing.register_bow("sling:sling", {
  description = "Sling",
  texture = "sling_sling_inv.png",
  wield_image = "sling_sling_wield.png",
  allow_shot = function(player, itemstack)
      return itemstack:get_name() ~= ""
  end,
  spawn_arrow_entity = function(pos, arrow, player)
    local obj = minetest.spawn_item(pos, arrow)
    local luaentity = obj:get_luaentity()
    luaentity.on_throw_sound = "throwing_build_arrow"
    return obj
  end
})
```

**Comment by tacotexmex** [comment]
That's alright with me! I'll try the above! 🎉

**Comment by paly2** [comment]
> Why not give the bow it's own on_throw_sound?

Why not, but what sound should be played if both are specified? The arrow on_throw_sound? The bow on_throw_sound? Or both?

**Comment by tacotexmex** [comment]
Both! But the bow sound could be called something else to distinguish itself, like `on_use_sound` or something. :)
