### ISSUE TITLE
Enable locally defined physics vars

### ISSUE THREAD

**Issue by tacotexmex** [Mynetest/throwing#10]
These three variables defines _all_ bows, right?
```
throwing.velocity_factor
throwing.horizontal_acceleration_factor
throwing.vertical_acceleration
```
How about enabling overrides on a bow level, perhaps even on an arrow level as well?

**Comment by paly2** [comment]
Good idea :-) These values can now be overridden in the bow definition. For the arrow, you can simply do it in the `on_throw` function.

**Comment by tacotexmex** [comment]
Sweet! This mod gets more flexible by the day.
