### ISSUE TITLE
Make it possible to use item inventory texture on arrows

### ISSUE THREAD

**Issue by tacotexmex** [Mynetest/throwing#12]
Currently when using `textures = {arrow}` as texture definition in `spawn_arrow_entity`, the wield item is used. Can you add a setting called `textures = {arrow_inv}` or similar so that the inventory image is used instead?

**Comment by paly2** [comment]
The `set_properties` function you're probably using in `spawn_arrow_entity` is part of the minetest API. The texture you specify depends on the `visual` field of your arrow definition.

See https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3946

**Comment by tacotexmex** [comment]
Okay, so that isn't easily fixed? No problem, it's a minor issue for me. [Mod published btw](https://github.com/tacotexmex/sling/)!

**Comment by paly2** [comment]
Well, the MT API does not provide any `visual` that would allow you to specify the inventory image the same way you can specify the wield image.

Nevertheless, the other `visual`s still allow you to specify another texture. The `sprite` visual makes a flat texture always looking are you (not too good I think for your sling). The `upright_sprite` is the same, except that you can go around it.
The `mesh` visual is undoubtedly the one that would make your sling best-looking, but it involves you to create a mesh file (e.g. using Blender). I've never done that, but [here](https://github.com/tenplus1/mobs_animal/blob/master/penguin.lua#L16) is an example (`mobs:register_mob` calls `minetest.register_entity` under the hood).
EDIT: sorry, the `mesh` visual is not suitable for your sling, given that all items don't have the same mesh and texture 😛 

Thank you for your mod! Starred it :D

**Comment by tacotexmex** [comment]
I'll just leave it be then. It's not worth the complexity 😁
Thanks! And thanks again for all the help.
