### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by SnarkBoojum** [Mynetest/throwing#17]
Hi,

could you please tag releases? It's a matter of doing something like "git tag 20180811 && git push --tags"...

I'd like to package that mod for the Debian distribution.

Thanks

**Comment by paly2** [comment]
Sure thanks, I'm fixing a couple bugs and releasing version 1.0. Would you prefer this mod to form a modpack with `throwing_arrows`?
EDIT: I decided to make them a modpack as they are mostly useful when used together ; however, if you think separate repositories are more appropriate, I can change it back.

**Comment by paly2** [comment]
I created the tag and named it `1.0`. Thanks for creating a package!

**Comment by SnarkBoojum** [comment]
Looks good ; notice that it spits warnings because minetest.setting_* functions are deprecated, so perhaps it will need updating to newer minetest versions at some point.

Thanks!

**Comment by tacotexmex** [comment]
Please don't make this into a modpack @paly2. Some people, like me, are only using the library part for git submodule inclusion in other projects.

Also: 
> Modpacks (groups of mods bundled together) are not permitted in minetest-mods, as they make management more difficult and prevent users from installing only parts of of a modpack.

**Comment by paly2** [comment]
Oh I see, I published both mods independently [here](https://git.fwhost.eu/MT-Eurythmia/throwing) and [here](https://git.fwhost.eu/MT-Eurythmia/throwing_arrows) so it remains convenient to use them separately. I still prefer to keep this repository as a modpack, as I believe what most users are looking for is a "classic" throwing mod with bows and arrows :smiley:

**Comment by tacotexmex** [comment]
>  I still prefer to keep this repository as a modpack, as I believe what most users are looking for is a "classic" throwing mod

You're probably right, but modpacks aren't permitted on minetest-mods so I suggest you do the inversed: modpack on your own host and the mods independently on minetest-mods.

**Comment by paly2** [comment]
> You're probably right, but modpacks aren't permitted on minetest-mods so I suggest you do the inversed: modpack on your own host and the mods independently on minetest-mods.

I understand the point and I'd totally agree if both mods could work and show functionality without the other one, but this rule seems flexible enough for mods that do not make much sense when used alone (e.g. Mesecons, Technic, castle and so on are all modpacks). I plan to continue the development in the upstream repositories so as to avoid "mak[ing] management more difficult and prevent[ing] users from installing only parts of a modpack" while keeping the modpack updated. I'd really like to keep it as a modpack inside minetest-mods so it is easier for users to install it: minetest-mods was created mostly as a single place to find mods, and it wouldn't make much sense if throwing needed to be downloaded from outside it as a modpack (and making two downloads just to have arrows and bows always seemed over-killing to me). Also, despite my best effort I do not always guarantee that the throwing API is backwards-compatible, and a modpack prevents any incompatibility.

**Comment by sofar** [comment]
> Mesecons, Technic, castle and so on are all modpacks

those are huge collections of software, and honestly they're mostly using modpacks to organize their code

Thos mod, however, could trivially be split up in 2, and nobody would bat an eye about it.

> Also, despite my best effort I do not always guarantee that the throwing API is backwards-compatible

This is in conflict with the manifest and goal of minetest-mods, and not desirable. If you can't guarantee the API is reasonably stable, perhaps we should consider removing these 2 mods from minetest-mods.
