### ISSUE TITLE
Cooldown

### ISSUE THREAD

**Issue by tacotexmex** [Mynetest/throwing#3]
Since spamming a bow with arrows may create lag on the server, a cooldown setting in the API would be useful.

**Comment by paly2** [comment]
Done. The cooldown can be set using the `cooldown` field in the definition table passed to `throwing.register_bow`. If it is not set, the value of the setting `throwing.bow_cooldown` is used.

**Comment by tacotexmex** [comment]
I had issues with making this work, but I'll test it more soon
