### ISSUE TITLE
Delay and delay sound

### ISSUE THREAD

**Issue by tacotexmex** [Mynetest/throwing#4]
For bows it takes some time to draw it, or for slingshots to draw the elastics back. A delay and delay sound would emulate this.  :bow_and_arrow:

**Comment by paly2** [comment]
Now implemented. The delay can simply be specified using the `delay` field. The sound can be specified using the bow `sound` field, since the bow sound starts to be played at the same moment as the delay starts.

**Comment by tacotexmex** [comment]
Cool! Thanks for being so responsive!
