### ISSUE TITLE
Enable sneak throwing

### ISSUE THREAD

**Issue by tacotexmex** [Mynetest/throwing#7]
If the mod listens to the sneak key when executing the throw function, perhaps it can be configurable to do something different, like throw a whole stack of the same item.

It could be called `allow_sneak_shot` to distinguish from the regular `allow_shot`. This way there can be two different throwing behaviors which is twice as fun!

**Comment by paly2** [comment]
No need to extend the API, it can easily be handled in the `allow_shot` function, e.g.
```lua
allow_shot = function(player, itemstack, index)
  if player:get_player_control().sneak then
    -- Do something
  else
    -- Do something else
  end
end
```

**Comment by tacotexmex** [comment]
Whoa, of course! :D I'm sorry for spamming with unnecessary requests, I'm just not very skilled in code yet.
