### ISSUE TITLE
Throw whole stack of the same item, multiple items

### ISSUE THREAD

**Issue by tacotexmex** [Mynetest/throwing#8]
If I want to throw a whole stack of an item is it possible with the current API? Perhaps a function like this can be stretched to support the throw of multiple items at once?

This is useful for when throwing a whole stack of items to a co-player and reduces the amount of entities being added in-world (1 stack containing 99 items instead of having to throw 99 items individually)

**Comment by paly2** [comment]
That's not implemented in the API, but you can use the `on_throw` and `on_hit` functions in your entity definition like this:
```lua
on_hit = function(pos, last_pos, node, object, hitter, data, self)
    minetest.spawn_item(last_pos, data.itemstack)
end,
on_throw = function(pos, thrower, next_index, data, self)
    data.itemstack = thrower:get_inventory():get_stack("main", next_index-1)
    thrower:get_inventory():set_stack("main", next_index-1, ItemStack(nil))
end
```

**Comment by tacotexmex** [comment]
I see! Ideally I'd like to it being made possible in `allow_shot` somehow. Like if it defaulted to 1 item, but could be configurable to X number of items, or all items in a single stack. But now I'm probably just being petty. 😄

**Comment by paly2** [comment]
That's quite hard to implement, since the API is not made to throw an ItemStack, but an entity. The behaviour of the arrow is generally not to drop a stack of items.

Nevertheless, extending `allow_shot` to make it tell to throwing how many items have to be removed from the stack is easy. I'm going to implement it.

**Comment by tacotexmex** [comment]
Cool but okay, so "how many items have to be removed from the stack" is doable, but having the same number being able to be picked up again is the hard part?

**Comment by paly2** [comment]
> but having the same number being able to be picked up again is the hard part

That's not really hard, but it doesn't fit at all with the API. For example, what would mean "a number of items being able to be picked up again" with, say, a dig arrow? This behaviour is part of the arrow definition, in the `on_hit` function, and cannot be handled by throwing itself.

**Comment by tacotexmex** [comment]
I see why my idea is counter-intuitive for the way you've structured the API, yes.

Where I come from with my sling idea is to extend the behavior of the default item dropping behavior triggered by the Q key.

In your example with the dig arrow I guess a number higher than 0 could possibly leave the arrow at the digged node and give that number of dig arrows back to the player on pickup. (Although that doesn't make sense for that particular arrow type at all)

**Comment by paly2** [comment]
Sorry, I think that handling this would increase the code complexity too much for a very specific kind of arrow 😃 

I extended the API, and I changed the params order. Now, the code should look like this:
```lua
throwing.register_bow("test:sling", {
  description = "Sling",
  texture = "sling_sling_inv.png",
  wield_image = "sling_sling_wield.png",
  allow_shot = function(player, itemstack, index)
    local ok = itemstack:get_name() ~= ""
    return ok, ok and ItemStack(nil)
  end,
  spawn_arrow_entity = function(pos, arrow, player)
    local obj = minetest.add_entity(pos, "sling:sling_entity")
    obj:set_properties{
      textures = {arrow},
      is_visible = true
    }
    return obj
  end
})

minetest.register_entity("sling:sling_entity", throwing.make_arrow_def{
  hp_max = 1,
  physical = false,
  weight = 5,
  makes_footstep_sound = false,
  automatic_rotate = false,
  visual = "wielditem",
  is_visible = false,

  target = throwing.target_node,
  on_hit_sound = "throwing_teleport_arrow",
  on_throw_sound = "throwing_build_arrow",
  on_hit = function(self, pos, last_pos, node, object, hitter, data)
    minetest.spawn_item(last_pos, data.itemstack)
  end,
  on_throw = function(self, pos, thrower, itemstack, index, data)
    data.itemstack = itemstack
  end
})
```
The code is not so complex, although not very easy to understand. The arrow stores the itemstack when it is thrown, and drops it when it hits its target.
Note: using `throwing.target_both` as `target` would be quite interesting too, don't you think?

**Comment by tacotexmex** [comment]
Yes, it's hard for me to follow what actually happens in the code. You'll definitively be a co-author of this mod if I use this. Still have to try that spawn_item for glitches first. I'll try it tomorrow. Thanks for all the work you put in!

**Comment by paly2** [comment]
When a player uses the sling, the first function called is `allow_shot`. First this function checks that we throw something:
```lua
local ok = itemstack:get_name() ~= ""
```
Now "ok" is simply a boolean that contains `true` if there's something to throw, and `false` otherwise.

Next we return this value and the new itemstack. `return ok, ok and ItemStack(nil)` is equivalent to:
```lua
if ok then
  return ok, ItemStack(nil) -- returns "true" and an empty ItemStack, that will replace the stack to be thrown
else
  return ok -- returns "false"
end
```

The next function that is called is `spawn_arrow_entity`. It simply makes a new entity to spawn, and sets its appearance so it corresponds to the thrown item.

Next, the entity function `on_throw` is called. This function stores the ItemStack to be thrown in its `data` (`data` is a table provided by throwing to avoid name collisions if the data was directly stored into the entity itself).

When the entity collides with a node, it is removed and `on_hit` is called. `on_hit` makes the ItemStack to spawn, as if it was dropped.

**Comment by tacotexmex** [comment]
Sweet, thank you for walking me through it. I'll study it further tomorrow!

**Comment by tacotexmex** [comment]
I've studied the last code you granted me and I ran it. However, it still does not throw whole stacks and I can't figure out why.

**Comment by paly2** [comment]
> it still does not throw whole stacks and I can't figure out why.

Strange, it works for me. Does it throw nothing or only one item? And what does the thrown itemstack contain (the full stack or just one item)?

**Comment by tacotexmex** [comment]
One thrown, one picked up.

**Comment by paly2** [comment]
Are you sure that you're using the latest throwing? Can you paste the exact code you're using?

**Comment by tacotexmex** [comment]
I'll double check for sure.

**Comment by tacotexmex** [comment]
I'm very sorry, you were totally right. It works as it should now. minetest.spawn isn't even that glitchy looking. Closing and ever thankful.
