### ISSUE TITLE
Delay bug/cheat

### ISSUE THREAD

**Issue by tacotexmex** [Mynetest/throwing#9]
When a delayed bow is fired, it is possible to switch active hotbar item while waiting for the delay to pass. This is because of the engine.

However, when the delay has finished and a hotbar switch has been performed meanwhile, strange things happen. In my case, the bow item is replicated into the active hotbar slot.

It seems to me that all logic of what arrow item to pull from what stack needs to all be calculated before the delay is put in place.

**Comment by paly2** [comment]
Your are absolutely right. Now fixed :-) There is another bug with the delay, which is that it is possible to start a new delay before the current one is actually finished. I'm fixing it.
EDIT: this 2nd bug is now fixed.

**Comment by tacotexmex** [comment]
Awesome!
